### ISSUE TITLE
I have a suggestion to make start bootstrap better

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [BlackrockDigital/startbootstrap#377]
I see you are adding theme ranking manually in this website but if you add it automatically like when someone downloads the theme then ranking number increase.

I think this helps even better than manually.

**Comment by Archie22is** [comment]
Create a PR and let's see what you have in mind - it might be useful elsewhere if the project owner thinks otherwise. I personally think you should go for it...

**Comment by davidtmiller** [comment]
The issue here would be creating some sort of tracking mechanism that would detect the download numbers and then feed those back through to the site itself. At the moment, running on Jekyll and GitHub Pages, this functionality is a bit out of reach - so I am just rank ordering them based on popularity - or newness in the case of new themes.

**Comment by davidtmiller** [comment]
We will be releasing this in our next big build coming sometime today or tomorrow!
